### ISSUE TITLE
Cannot find dag files on my repo when using this GH Action

### ISSUE THREAD

**Issue by idanb11** [jayamanikharyono/airflow-dag-action#34]
Hello @jayamanikharyono ,

I have an issue with this GH action, 
i am trying a very simple and standard airflow-dag-action like so:

```
jobs:
  validate-dag-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          path: airflow
      - name: Validate DAGs
        uses: jayamanikharyono/airflow-dag-action@v2.3
        with:
          requirementsFile: airflow/dags/requirements.txt
          dagPaths: airflow/dags
          varFile: airflow/dags/variables.json
          accessToken: ${{ secrets.GITHUB_TOKEN }}

```

and i am getting the following errors:

```
Requirements path : airflow/dags/requirements.txt
DAGs directory : airflow/dags
Variable path : airflow/dags/variables.json
Connections path : airflow/dags/conns.json
Plugin directory : airflow/dags/plugins
Load examples : False
WARNING: The directory '/github/home/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'airflow/dags/requirements.txt'


Missing variables file.
Missing connections file.
Pytest exited 0
```
